# Generated by Django 3.2.9 on 2022-05-14 14:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_remove_product_authors_product_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 14, 0, 42, 483316, tzinfo=utc), verbose_name='date published'),
        ),
    ]
