# Generated by Django 3.2.9 on 2022-05-14 20:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_auto_20220514_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Product.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 20, 42, 56, 63074, tzinfo=utc), verbose_name='date published'),
        ),
    ]
