# Generated by Django 4.0.4 on 2022-06-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_category_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.FileField(upload_to='media/'),
        ),
    ]
