# Generated by Django 4.0.4 on 2022-05-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_surname', models.CharField(max_length=200)),
                ('user_email', models.CharField(max_length=200)),
                ('user_login', models.CharField(max_length=200)),
            ],
        ),
    ]
